Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2023-08, with the labels that each got.

#1844 fix:delete consensus level
  src/pika_admin.cc
  src/pika_client_conn.cc
  src/pika_consensus.cc
  src/pika_repl_bgworker.cc
  src/pika_repl_client.cc
  src/pika_repl_server.cc
  src/pika_server.cc
  src/pika_slot.cc
Labels: bug

#1852 fix:delete_consensus_level
  include/pika_consensus.h
  include/pika_rm.h
  include/pika_server.h
  src/pika_client_conn.cc
  src/pika_consensus.cc
  src/pika_repl_bgworker.cc
  src/pika_rm.cc
  src/pika_server.cc
Labels: enhancement

#1859 fix:shutdown&&slaveof no one too slow
  src/rsync_client.cc
  src/rsync_server.cc
Labels: bug

#1792 add go integrate test
  .github/workflows/pika.yml
  src/pika_list.cc
  tests/integration/csanning_test.go
  tests/integration/geo_test.go
  tests/integration/go.mod
  tests/integration/hash_test.go
  tests/integration/hyperloglog_test.go
  tests/integration/integrate_test.sh
  tests/integration/list_test.go
  tests/integration/main_test.go
  tests/integration/options.go
  tests/integration/server_test.go
  tests/integration/set_test.go
  tests/integration/slowlog_test.go
  tests/integration/start_master_and_slave.sh
  tests/integration/string_test.go
  tests/integration/tcl/aof-race.tcl
  tests/integration/tcl/aof.tcl
  tests/integration/tcl/convert-zipmap-hash-on-load.tcl
  tests/integration/tcl/rdb.tcl
  tests/integration/tcl/redis-cli.tcl
  tests/integration/tcl/replication-2.tcl
  tests/integration/tcl/replication-3.tcl
  tests/integration/tcl/replication-4.tcl
  tests/integration/tcl/replication-psync.tcl
  tests/integration/tcl/replication.tcl
  tests/integration/zset_test.go
Labels: enhancement

#1839 doc: update API.md to 3.5.0
  docs/ops/API.md
Labels: document

#1843 feat: add diskrecovery command
  docs/ops/APIDifference.md
  include/pika_admin.h
  include/pika_command.h
  include/pika_db.h
  include/pika_server.h
  src/pika_admin.cc
  src/pika_command.cc
  src/pika_db.cc
  src/pika_server.cc
Labels: new-feature

#1832 doc: Add migrateslotCommand.MD
  docs/ops/migrateslotCommand.md
Labels: document

#1828 doc: Add v3.5.0 CHANGELOG.MD
  CHANGELOG.MD
  CHANGELOG_CN.MD
Labels: document

#1838 doc: update API.md to unstable
  docs/ops/API.md
Labels: document

#1788 Add helm install based on kubeblocks
  tools/kubeblocks_helm/README.md
  tools/kubeblocks_helm/pika-cluster/.helmignore
  tools/kubeblocks_helm/pika-cluster/Chart.yaml
  tools/kubeblocks_helm/pika-cluster/templates/NOTES.txt
  tools/kubeblocks_helm/pika-cluster/templates/_helpers.tpl
  tools/kubeblocks_helm/pika-cluster/templates/cluster.yaml
  tools/kubeblocks_helm/pika-cluster/templates/role.yaml
  tools/kubeblocks_helm/pika-cluster/templates/rolebinding.yaml
  tools/kubeblocks_helm/pika-cluster/templates/serviceaccount.yaml
  tools/kubeblocks_helm/pika-cluster/values.yaml
  tools/kubeblocks_helm/pika/.helmignore
  tools/kubeblocks_helm/pika/Chart.yaml
  tools/kubeblocks_helm/pika/config/codis-dashboard.tpl
  tools/kubeblocks_helm/pika/config/codis-proxy.tpl
  tools/kubeblocks_helm/pika/config/pika-config.tpl
  tools/kubeblocks_helm/pika/templates/_helpers.tpl
  tools/kubeblocks_helm/pika/templates/clusterdefinition.yaml
  tools/kubeblocks_helm/pika/templates/clusterversion.yaml
  tools/kubeblocks_helm/pika/templates/configmap.yaml
  tools/kubeblocks_helm/pika/values.yaml
Labels: enhancement

#1890 ci: add nightly and release image build action
  .github/workflows/codis.yml
  .github/workflows/pika.yml
  .github/workflows/publish_nightly_docker_image.yml
  .github/workflows/publish_release_docker_image.yml
  Dockerfile
  codis/Dockerfile
Labels: docker, CI

#1931 operator: automatic registration for the Pika service
  codis/Dockerfile
  tools/kubeblocks_helm/pika-cluster/templates/cluster.yaml
  tools/kubeblocks_helm/pika-cluster/values.yaml
  tools/kubeblocks_helm/pika/script/admin.sh
  tools/kubeblocks_helm/pika/templates/clusterdefinition.yaml
  tools/kubeblocks_helm/pika/templates/clusterversion.yaml
  tools/kubeblocks_helm/pika/templates/script.yaml
Labels: enhancement, k8s

#1935 fix: #1934
  .github/workflows/pika.yml
  .github/workflows/publish_nightly_docker_image.yml
  .github/workflows/publish_release_docker_image.yml
  src/pika_monotonic_time.cc
Labels: bug, compile
