Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2023-12, with the labels that each got.

#74 chore: ci optimize check coding format
  .github/workflows/pikiwidb.yml
  ci/build.sh
Labels: enhancement

#83 chore: release add build app
  .github/workflows/release.yml
  build.sh
Labels: ✏️ Feature

#88 fix: build error of new pull request
  src/cmd_hash.cc
Labels: ☢️ Bug

#59 feat: string cmd incr
  src/base_cmd.h
  src/cmd_kv.cc
  src/cmd_kv.h
  src/cmd_table_manager.cc
  src/command.cc
Labels: ✏️ Feature, 0.1.0, core
