Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2023-09, with the labels that each got.

#1585 Feature/txn
  include/pika_admin.h
  include/pika_client_conn.h
  include/pika_command.h
  include/pika_db.h
  include/pika_kv.h
  include/pika_list.h
  include/pika_rm.h
  include/pika_server.h
  include/pika_slot.h
  include/pika_transaction.h
  src/net/src/dispatch_thread.cc
  src/net/src/dispatch_thread.h
  src/net/src/worker_thread.cc
  src/net/src/worker_thread.h
  src/pika_admin.cc
  src/pika_client_conn.cc
  src/pika_command.cc
  src/pika_consensus.cc
  src/pika_kv.cc
  src/pika_list.cc
  src/pika_repl_bgworker.cc
  src/pika_slot.cc
  src/pika_transaction.cc
  src/storage/include/storage/storage.h
  src/storage/src/storage.cc
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/txn_test.go
Labels: enhancement

#2014 Feature:Add the option to set the maximum number of background jobs
  conf/pika.conf
  docs/ops/config.md
  include/pika_conf.h
  src/pika_admin.cc
  src/pika_conf.cc
  src/pika_server.cc
  tests/assets/default.conf
  tests/conf/pika.conf
  tools/kubeblocks_helm/pika/config/pika-config.tpl
  tools/pika_operator/examples/pika-minikube/pika-cm.yaml
  tools/pika_operator/examples/pika-pvc/pika-cm.yaml
Labels: new-feature

#2015 Feature: The WAL command can be dynamically disabled
  docs/ops/APIDifference.md
  include/pika_admin.h
  include/pika_command.h
  src/pika_admin.cc
  src/pika_command.cc
  src/storage/include/storage/storage.h
  src/storage/src/redis.cc
  src/storage/src/redis.h
  src/storage/src/storage.cc
Labels: new-feature

#2011 replace hiredis for compile error in macos
  .github/workflows/pika.yml
  CMakeLists.txt
  tools/benchmark_client/CMakeLists.txt
  tools/benchmark_client/benchmark_client.cc
  tools/pika-port/pika_port_3/CMakeLists.txt
  tools/pika-port/pika_port_3/main.cc
  tools/pika_to_txt/CMakeLists.txt
  tools/rdb_to_pika/CMakeLists.txt
  tools/rdb_to_pika/protocoltopika.cc
  tools/txt_to_pika/CMakeLists.txt
Labels: bug

#2018 doc: Add v3.5.1 CHANGELOG
  CHANGELOG.MD
  CHANGELOG_CN.MD
Labels: document
