Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-07, with the labels that each got.

#2764 docs: v4.0.0 changelog
  CHANGELOG.MD
  CHANGELOG_CN.MD
Labels: 📒 Documentation, 4.0.0

#2785 fix: delete iter before returns
  src/storage/src/redis_strings.cc
Labels: bug, ☢️ Bug, 4.0.0

#2788 docs: 4.0.0 change log patch to add PR 2785
  CHANGELOG.MD
  CHANGELOG_CN.MD
Labels: 📒 Documentation

#2786 fix: delete iter before return for 3.5 branch
  src/storage/src/redis_hashes.cc
  src/storage/src/redis_lists.cc
  src/storage/src/redis_sets.cc
  src/storage/src/redis_streams.cc
  src/storage/src/redis_strings.cc
  src/storage/src/redis_zsets.cc
Labels: ☢️ Bug

#2797 feat: add more cache info
  src/pika_admin.cc
  src/storage/include/storage/storage.h
Labels: ✏️ Feature, 4.0.1

#2813 fix:slave_prorority need to be 100 when used redis sentinel
  include/pika_conf.h
Labels: ☢️ Bug, 3.5.5, 4.0.1

#2790 fix: successive exec of flushdb may cause delete old db fail
  include/pika_admin.h
  src/pika_admin.cc
  src/pika_db.cc
  src/pika_server.cc
  src/pika_transaction.cc
Labels: ☢️ Bug, 3.5.5, 4.0.1

#2777 fix: PkPatternMatchDel inconsistent between rediscache and db
  CMakeLists.txt
  include/pika_admin.h
  src/pika_admin.cc
  src/pika_command.cc
  src/storage/include/storage/storage.h
  src/storage/src/redis.h
  src/storage/src/redis_strings.cc
  src/storage/src/storage.cc
  src/storage/tests/keys_test.cc
Labels: ☢️ Bug, 3.5.5, 4.0.1
