Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-03, with the labels that each got.

#2435 fix: ci replication go test failed problem
  tests/integration/cache_test.go
  tests/integration/csanning_test.go
  tests/integration/geo_test.go
  tests/integration/hash_test.go
  tests/integration/hyperloglog_test.go
  tests/integration/list_test.go
  tests/integration/options.go
  tests/integration/pubsub_test.go
  tests/integration/replication_test.go
  tests/integration/server_test.go
  tests/integration/set_test.go
  tests/integration/slowlog_test.go
  tests/integration/start_master_and_slave.sh
  tests/integration/stream_test.go
  tests/integration/string_test.go
  tests/integration/txn_test.go
  tests/integration/zset_test.go
Labels: ☢️ Bug, 🧹 Updates, 3.5.3, test

#2443 fix:353version
  include/pika_version.h
Labels: ☢️ Bug

#2449 fix: ACL user authentication errors
  src/pika_client_conn.cc
Labels: ☢️ Bug

#2445 fix: change pika version to 3.6.0
  include/pika_version.h
Labels: ☢️ Bug

#2455 feat: add Rename Command
  conf/pika.conf
  include/pika_cmd_table_manager.h
  include/pika_conf.h
  src/pika.cc
  src/pika_cmd_table_manager.cc
  src/pika_conf.cc
Labels: ✏️ Feature, 3.5.3

#2462 feat: add rename command
  conf/pika.conf
  include/pika_cmd_table_manager.h
  include/pika_conf.h
  src/pika.cc
  src/pika_client_conn.cc
  src/pika_cmd_table_manager.cc
  src/pika_conf.cc
Labels: ✏️ Feature

#2472 fix: rocksdb metrics error(#2471)
  .gitignore
  src/storage/src/storage.cc
Labels: ☢️ Bug, 3.5.3

#2475 fix: support removing pika instance from codis dashboard before pod stop
  tools/kubeblocks_helm/pika/templates/clusterdefinition.yaml
Labels: ☢️ Bug

#2476 fix: support saving pika config to hostpath
  tools/kubeblocks_helm/pika/templates/clusterdefinition.yaml
Labels: ☢️ Bug

#2474 fix: no namespace in configmap, so remove the namespace
  tools/kubeblocks_helm/pika/templates/componentdefinition-codis-dashboard.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-codis-proxy.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-pika-group.yaml
Labels: ☢️ Bug, 🧹 Updates

#2458 fix: move Dockerfile and build_docker.sh into docker subdirectory
  .github/workflows/publish_nightly_docker_image.yml
  .github/workflows/publish_release_docker_image.yml
  docker/Dockerfile_pika
  docker/build_pika_docker.sh
Labels: ☢️ Bug

#2451 feat: support building pika_exporter docker image
  .dockerignore
  .github/workflows/publish_nightly_docker_image.yml
  .github/workflows/publish_release_docker_image.yml
  docker/Dockerfile_pika_exporter
  docker/build_pika_exporter_docker.sh
  tools/pika_exporter/Makefile
Labels: ✏️ Feature

#2468 fix: add rename go test
  tests/conf/pika.conf
  tests/integration/options.go
  tests/integration/renamecommand_test.go
  tests/integration/start_master_and_slave.sh
Labels: 🧹 Updates, 3.5.3, test

#2473 feat: support deploying pika_exporter components using kubeblocks
  tools/kubeblocks_helm/pika-cluster/templates/cluster.yaml
  tools/kubeblocks_helm/pika-cluster/values.yaml
  tools/kubeblocks_helm/pika/config/exporter-info.tpl
  tools/kubeblocks_helm/pika/dashboards/pika.json
  tools/kubeblocks_helm/pika/templates/_helpers.tpl
  tools/kubeblocks_helm/pika/templates/clusterdefinition.yaml
  tools/kubeblocks_helm/pika/templates/clusterversion.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-pika-exporter.yaml
  tools/kubeblocks_helm/pika/templates/configmap.yaml
  tools/kubeblocks_helm/pika/templates/grafana/configmap-dashboards.yaml
  tools/kubeblocks_helm/pika/values.yaml
Labels: ✏️ Feature

#2489 fix:delete migrate log
  src/pika_slot_command.cc
Labels: ☢️ Bug

#2495 feat: add acl test
  tests/integration/acl_test.go
  tests/integration/options.go
  tests/integration/start_master_and_slave.sh
Labels: ✏️ Feature, 🧹 Updates, 3.5.3

#2485 fix:Binlog is written repeatedly && not delete cache
  src/pika_slot_command.cc
Labels: ☢️ Bug, 3.5.3

#2502 test: add codis integration test
  .github/workflows/pika.yml
  codis/go.mod
  codis/go.sum
  codis/pkg/proxy/mapper.go
  tests/integration/acl_test.go
  tests/integration/codis_test.go
  tests/integration/csanning_test.go
  tests/integration/geo_test.go
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/hash_test.go
  tests/integration/hyperloglog_test.go
  tests/integration/main_test.go
  tests/integration/options.go
  tests/integration/pubsub_test.go
  tests/integration/replication_test.go
  tests/integration/set_test.go
  tests/integration/slowlog_test.go
  tests/integration/start_codis.sh
  tests/integration/stream_test.go
  tests/integration/string_test.go
  tests/integration/txn_test.go
  tests/integration/zset_test.go
Labels: ✏️ Feature, 🧹 Updates, 3.5.3

#2510 fix: fix Getrange bug
  src/storage/src/redis_strings.cc
Labels: ☢️ Bug, 3.6.0

#2517 chore: delete cache log
  src/pika_server.cc
Labels: ☢️ Bug, 3.5.3

#2426 feat: replace rocksdb with rocksdb-cloud
  CMakeLists.txt
  conf/pika.conf
  include/pika_conf.h
  src/pika_conf.cc
  src/pika_server.cc
  src/storage/include/storage/storage.h
  src/storage/src/base_filter.h
  src/storage/src/lists_filter.h
  src/storage/src/redis.cc
  src/storage/src/redis.h
  src/storage/src/storage.cc
  src/storage/src/zsets_filter.h
  src/storage/tests/CMakeLists.txt
  src/storage/tests/hashes_test.cc
  src/storage/tests/hyperloglog_test.cc
  src/storage/tests/keys_test.cc
  src/storage/tests/lists_filter_test.cc
  src/storage/tests/lists_test.cc
  src/storage/tests/sets_test.cc
  src/storage/tests/strings_test.cc
  src/storage/tests/zsets_test.cc
  tests/conf/pika.conf
Labels: ✏️ Feature, 3.5.4

#2529 fix: fix lock bug
  .github/workflows/pika.yml
  codis/config/proxy.toml
  include/pika_db.h
  include/pika_repl_server_conn.h
  src/pika_admin.cc
  src/pika_command.cc
  src/pika_db.cc
  src/pika_repl_bgworker.cc
  src/pika_server.cc
  src/pika_transaction.cc
  tests/integration/main_test.go
  tests/integration/replication_test.go
Labels: ☢️ Bug

#2540 fix: added some disable command additions to the rename-command
  conf/pika.conf
  tests/integration/options.go
  tests/integration/renamecommand_test.go
  tests/integration/replication_rename_test.go
  tests/integration/start_master_and_slave.sh
Labels: ✏️ Feature, ☢️ Bug, 3.5.3

#2535 chore: release add centos for os and optimization
  .github/workflows/release.yml
  ci/release-build.sh
Labels: ✏️ Feature, 4.0.0

#2528 test: Comment unavailable tcl test cases
  .gitignore
  tests/unit/introspection.tcl
Labels: 🧹 Updates, 📒 Documentation

#2539 fix:MoveConnOut(it->second[i]) will cause CloseFd(it->second[i]) to go out of bounds
  src/net/src/net_pubsub.cc
  src/pika_conf.cc
Labels: ☢️ Bug, 3.5.4, 4.0.0

#2544 fix:353 changelog
  CHANGELOG.MD
  CHANGELOG_CN.MD
Labels: ☢️ Bug, 📒 Documentation, 3.5.3

#2553 fix: modify the function name from "GetFlushDname" to "GetFlushDBname"
  include/pika_admin.h
  src/pika_client_conn.cc
Labels: ☢️ Bug

#2556 fix: use the built-in CMake variable to get the system arch.
  CMakeLists.txt
Labels: ☢️ Bug

#2533 fix: flushdb and flushall bug
  include/pika_admin.h
  include/pika_db.h
  include/pika_transaction.h
  src/pika_admin.cc
  src/pika_db.cc
  src/pika_transaction.cc
  tests/integration/main_test.go
  tests/integration/replication_test.go
Labels: ☢️ Bug, 3.5.4, 4.0.0

#2559 feat: change version to 4.0.0
  include/pika_server.h
  include/pika_version.h
Labels: ✏️ Feature
