Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-12, with the labels that each got.

#2962 fix: fix user ERR NOAUTH Authentication required
  conf/pika.conf
  src/acl.cc
Labels: ☢️ Bug

#2968 feat:finish backup and restore
  tools/kubeblocks_helm/BackupRepo_config
  tools/kubeblocks_helm/README.md
  tools/kubeblocks_helm/install.sh
  tools/kubeblocks_helm/install_ms.sh
  tools/kubeblocks_helm/installdebug.sh
  tools/kubeblocks_helm/pika-master-slave-cluster/templates/role.yaml
  tools/kubeblocks_helm/pika-master-slave/dataprotection/backup.sh
  tools/kubeblocks_helm/pika-master-slave/dataprotection/restore.sh
  tools/kubeblocks_helm/pika-master-slave/templates/backupactionset.yaml
  tools/kubeblocks_helm/pika-master-slave/templates/backuppolicytemplate.yaml
  tools/kubeblocks_helm/pika-master-slave/templates/componentdefinition-pika.yaml
  tools/kubeblocks_helm/uninstall.sh
  tools/kubeblocks_helm/uninstall_ms.sh
Labels: 3.5.6, 4.0.2

#2966 feat:zmax && zmin
  include/pika_cache.h
  include/pika_zset.h
  src/cache/include/cache.h
  src/cache/src/zset.cc
  src/pika_cache.cc
  src/pika_command.cc
  src/pika_zset.cc
  tests/integration/zset_test.go
Labels: ✏️ Feature, 3.5.6, 4.0.2

#2965 feat: support dynamically change max-subcompactions using config set command
  src/pika_admin.cc
  src/storage/src/options_helper.h
Labels: ✏️ Feature, 3.5.6, 4.0.2

#2963 feat: make log-retention-time dynamically changeable
  include/pika_conf.h
  src/pika_admin.cc
Labels: ✏️ Feature, 3.5.6, 4.0.2

#2973 fix: persist the salveof conf item when slaveof no one is executed
  include/pika_conf.h
  src/pika_admin.cc
  src/pika_conf.cc
Labels: ☢️ Bug

#2964 feat: add log-net-activities configuration
  conf/pika.conf
  include/pika_conf.h
  include/pika_dispatch_thread.h
  include/pika_server.h
  src/net/include/server_thread.h
  src/net/src/dispatch_thread.cc
  src/net/src/server_thread.cc
  src/pika_admin.cc
  src/pika_conf.cc
  src/pika_dispatch_thread.cc
  src/pika_server.cc
Labels: ✏️ Feature, 3.5.6, 4.0.2

#2976 fix: rpoplpush cause inconsistency in cache mode
  include/pika_list.h
  src/pika_command.cc
  src/pika_list.cc
Labels: ☢️ Bug, 3.5.6, 4.0.2

#2977 feat:4.0.2 changelog && add some test
  CHANGELOG.MD
  CHANGELOG_CN.MD
  tests/integration/list_test.go
Labels: ✏️ Feature, 🧹 Updates, 📒 Documentation

#2979 fix:release wrong
  .github/workflows/release.yml
Labels: ☢️ Bug

#2985 fix:lpop and lpushx test
  tests/integration/list_test.go
Labels: ☢️ Bug, 🧹 Updates
