Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-10, with the labels that each got.

#2579 feat: Add Keyspace hits metrics for set
  include/pika_command.h
  include/pika_server.h
  include/pika_statistic.h
  src/pika_admin.cc
  src/pika_command.cc
  src/pika_server.cc
  src/pika_set.cc
  tests/integration/integrate_test.sh
  tests/integration/server_test.go
Labels: ✏️ Feature, 4.0.1

#2904 fix: an edge case of kill connctions casued by unnecessary shared_ptr ref count
  src/net/src/worker_thread.cc
Labels: ☢️ Bug

#2924 fix:fix CI
  .github/workflows/pika.yml
Labels: ☢️ Bug

#2906 feat: Refactor pika binlog to achieve idempotency and master-slave consistency (ospp 2024)
  include/pika_cache.h
  include/pika_command.h
  include/pika_hash.h
  include/pika_hyperloglog.h
  include/pika_kv.h
  include/pika_set.h
  include/pika_zset.h
  include/wal_edit.h
  src/net/src/worker_thread.cc
  src/pika_cache.cc
  src/pika_command.cc
  src/pika_hash.cc
  src/pika_hyperloglog.cc
  src/pika_kv.cc
  src/pika_set.cc
  src/pika_slot_command.cc
  src/pika_zset.cc
  src/storage/include/storage/storage.h
  src/storage/src/redis.h
  src/storage/src/redis_hashes.cc
  src/storage/src/redis_sets.cc
  src/storage/src/redis_strings.cc
  src/storage/src/redis_zsets.cc
  src/storage/src/storage.cc
  src/storage/tests/hashes_test.cc
  src/storage/tests/keys_test.cc
  src/storage/tests/sets_test.cc
  src/storage/tests/strings_test.cc
  src/storage/tests/zsets_test.cc
  tests/integration/codis_test.go
  tests/integration/rsync_dynamic_reconfig.go
  tests/integration/zset_test.go
Labels: ✏️ Feature, 🧹 Updates

#2913 feat: add proxy module (ospp 2024)
  src/proxy/brpc_redis.cc
  src/proxy/brpc_redis.h
  src/proxy/proxy_base_cmd.cc
  src/proxy/proxy_base_cmd.h
  src/proxy/proxy_cmd_kv.cc
  src/proxy/proxy_cmd_kv.h
  src/proxy/router.cc
  src/proxy/router.h
  src/proxy/task_manager.cc
  src/proxy/task_manager.h
Labels: ✏️ Feature

#2816 feat: a new strategy for auto compaction (ospp 2024)
  conf/pika.conf
  include/pika_conf.h
  include/pika_db.h
  include/pika_server.h
  src/pika_conf.cc
  src/pika_db.cc
  src/pika_server.cc
  src/storage/include/storage/storage.h
  src/storage/src/redis.cc
  src/storage/src/redis.h
  src/storage/src/storage.cc
Labels: ✏️ Feature, 4.0.1

#2914 feat: add support for vector search (ospp 2024)
  src/storage/include/storage/storage.h
  src/storage/include/storage/storage_define.h
  src/storage/src/base_value_format.h
  src/storage/src/coding.h
  src/storage/src/redis.cc
  src/storage/src/redis.h
  src/storage/src/redis_search,cc
  src/storage/src/storage.cc
Labels: ✏️ Feature, 📒 Documentation

#2933 Revert "feat: add support for vector search (ospp 2024)"
  src/storage/include/storage/storage.h
  src/storage/include/storage/storage_define.h
  src/storage/src/base_value_format.h
  src/storage/src/coding.h
  src/storage/src/redis.cc
  src/storage/src/redis.h
  src/storage/src/redis_search,cc
  src/storage/src/storage.cc
Labels: ✏️ Feature, Invalid PR Title

#2934 fix: compilation error
  src/storage/src/redis.cc
Labels: ☢️ Bug

#2648 feat:change thread sheduling method in ThreadPool class (ospp 2024)
  src/net/include/likely.h
  src/net/include/net_define.h
  src/net/include/random.h
  src/net/include/thread_pool.h
  src/net/src/thread_pool.cc
  tests/integration/start_codis.sh
Labels: ✏️ Feature, 4.0.1
