Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-09, with the labels that each got.

#2888 fix: add a function for washing data after upgrading version from 4.0.0 to 4.0.1
  conf/pika.conf
  include/pika_conf.h
  include/pika_db.h
  src/pika.cc
  src/pika_conf.cc
  src/pika_db.cc
  src/storage/include/storage/storage.h
  src/storage/src/base_data_value_format.h
  src/storage/src/redis.h
  src/storage/src/storage.cc
Labels: ✏️ Feature, ☢️ Bug

#2857 fix: change storage ttl time from seconds to milliseconds
  .github/workflows/pika.yml
  include/pika_cache.h
  include/pika_kv.h
  src/net/examples/performance/server.cc
  src/pika_admin.cc
  src/pika_bit.cc
  src/pika_cache.cc
  src/pika_cache_load_thread.cc
  src/pika_conf.cc
  src/pika_geo.cc
  src/pika_kv.cc
  src/pika_list.cc
  src/pika_server.cc
  src/pika_zset.cc
  src/pstd/include/env.h
  src/pstd/src/env.cc
  src/storage/include/storage/storage.h
  src/storage/src/base_data_value_format.h
  src/storage/src/base_filter.h
  src/storage/src/base_meta_value_format.h
  src/storage/src/base_value_format.h
  src/storage/src/lists_filter.h
  src/storage/src/lists_meta_value_format.h
  src/storage/src/redis.h
  src/storage/src/redis_hashes.cc
  src/storage/src/redis_lists.cc
  src/storage/src/redis_sets.cc
  src/storage/src/redis_streams.cc
  src/storage/src/redis_strings.cc
  src/storage/src/redis_zsets.cc
  src/storage/src/storage.cc
  src/storage/src/strings_filter.h
  src/storage/src/strings_value_format.h
  src/storage/src/zsets_filter.h
  src/storage/tests/keys_test.cc
  src/storage/tests/lists_filter_test.cc
  src/storage/tests/strings_filter_test.cc
  src/storage/tests/strings_test.cc
Labels: ☢️ Bug

#2896 fix:Segmentation fault in zremrangebyrank
  src/pika_zset.cc
  tests/integration/zset_test.go
Labels: ☢️ Bug

#2899 fix:caculate memory
  src/pika_admin.cc
Labels: ☢️ Bug

#2902 docs:4.0.1 changelog
  CHANGELOG.MD
  CHANGELOG_CN.MD
  tests/integration/zset_test.go
Labels: document, 📒 Documentation, 4.0.1

#2849 feat: dont store cmd(Get/Set/Hget/Hset) with too large key in cache
  include/pika_command.h
  include/pika_conf.h
  include/pika_hash.h
  include/pika_kv.h
  src/cache/include/config.h
  src/pika_client_conn.cc
  src/pika_conf.cc
  src/pika_hash.cc
  src/pika_kv.cc
Labels: ✏️ Feature, ☢️ Bug, 4.0.1

#2860 feat:Update kubeblocks version to 0.9
  tools/kubeblocks_helm/README.md
  tools/kubeblocks_helm/pika-cluster/Chart.yaml
  tools/kubeblocks_helm/pika-cluster/templates/cluster.yaml
  tools/kubeblocks_helm/pika/.helmignore
  tools/kubeblocks_helm/pika/Chart.yaml
  tools/kubeblocks_helm/pika/script/admin.sh
  tools/kubeblocks_helm/pika/templates/clusterdefinition.yaml
  tools/kubeblocks_helm/pika/templates/clusterversion.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-codis-dashboard.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-codis-fe.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-codis-proxy.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-pika-etcd.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-pika-exporter.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-pika-group.yaml
  tools/kubeblocks_helm/pika/templates/componentversion-codis-dashboard.yaml
  tools/kubeblocks_helm/pika/templates/componentversion-codis-fe.yaml
  tools/kubeblocks_helm/pika/templates/componentversion-codis-proxy.yaml
  tools/kubeblocks_helm/pika/templates/componentversion-pika-etcd.yaml
  tools/kubeblocks_helm/pika/templates/componentversion-pika-exporter.yaml
  tools/kubeblocks_helm/pika/templates/componentversion-pika-group.yaml
  tools/kubeblocks_helm/pika/templates/configmap.yaml
  tools/kubeblocks_helm/pika/templates/script.yaml
  tools/kubeblocks_helm/pika/values.yaml
Labels: ✏️ Feature, 🧹 Updates, 📒 Documentation, 4.0.1

#2901 feat:add test for redis commands, including LPush, RPushX, BgSave, FlushDb and SetEx
  tests/integration/list_test.go
  tests/integration/server_test.go
  tests/integration/string_test.go
Labels: ✏️ Feature, 🧹 Updates

#2910 ci: upgrade actions
  .github/workflows/codeql.yml
  .github/workflows/codis.yml
  .github/workflows/pika.yml
  .github/workflows/publish_nightly_docker_image.yml
  .github/workflows/publish_release_docker_image.yml
  .github/workflows/release.yml
  .github/workflows/tools_go.yml
Labels: 🤖 Dependencies

#2903 feat:pika-master-slave-cluster in kb
  tools/kubeblocks_helm/README.md
  tools/kubeblocks_helm/pika-master-slave-cluster/.helmignore
  tools/kubeblocks_helm/pika-master-slave-cluster/Chart.yaml
  tools/kubeblocks_helm/pika-master-slave-cluster/templates/_helpers.tpl
  tools/kubeblocks_helm/pika-master-slave-cluster/templates/cluster.yaml
  tools/kubeblocks_helm/pika-master-slave-cluster/templates/role.yaml
  tools/kubeblocks_helm/pika-master-slave-cluster/templates/rolebinding.yaml
  tools/kubeblocks_helm/pika-master-slave-cluster/templates/serviceaccount.yaml
  tools/kubeblocks_helm/pika-master-slave-cluster/values.yaml
  tools/kubeblocks_helm/pika-master-slave/.helmignore
  tools/kubeblocks_helm/pika-master-slave/Chart.yaml
  tools/kubeblocks_helm/pika-master-slave/config/pika-config.tpl
  tools/kubeblocks_helm/pika-master-slave/templates/_helpers.tpl
  tools/kubeblocks_helm/pika-master-slave/templates/clusterdefinition.yaml
  tools/kubeblocks_helm/pika-master-slave/templates/componentdefinition-pika.yaml
  tools/kubeblocks_helm/pika-master-slave/templates/componentversion-pika.yaml
  tools/kubeblocks_helm/pika-master-slave/templates/configmap.yaml
  tools/kubeblocks_helm/pika-master-slave/values.yaml
Labels: new-feature, k8s, ✏️ Feature, 📒 Documentation

#2915 docs:Pika wechat
  docs/images/pika-wechat-cn.png
  docs/images/pika-wechat.png
Labels: 📒 Documentation

#2917 docs:pika wechat
  docs/images/pika-wechat-cn.png
  docs/images/pika-wechat.png
Labels: 📒 Documentation
