Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-05, with the labels that each got.

#2644 fix:slave parse tnx binlog failed test
  tests/integration/replication_test.go
Labels: ☢️ Bug, 🧹 Updates

#2656 fix: add a user-friendly repl metric "repl_connect_status" in the resp of info command
  src/pika_admin.cc
Labels: ✏️ Feature, 4.0.0, 3.5.5

#2657 fix: remove an unnecessary unlock operation in rsync throttle
  src/throttle.cc
Labels: ☢️ Bug, 🧹 Updates, 4.0.0, 3.5.5
