Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-02, with the labels that each got.

#2349 feat: recover it when the goroutine caused some panic
  codis/pkg/topom/topom.go
  codis/pkg/utils/runtime/goroutine.go
Labels: ✏️ Feature

#2395 feat:add 3.5.3 changelog
  CHANGELOG.MD
  CHANGELOG_CN.MD
Labels: ✏️ Feature, 📒 Documentation, 3.5.3

#2409 fix:slave instance apply db not used lock
  src/pika_repl_bgworker.cc
Labels: ☢️ Bug

#2411 feat: pika supports kubeblocks component definition api
  tools/kubeblocks_helm/pika-cluster/templates/_helpers.tpl
  tools/kubeblocks_helm/pika-cluster/templates/cluster.yaml
  tools/kubeblocks_helm/pika-cluster/values.yaml
  tools/kubeblocks_helm/pika/script/admin.sh
  tools/kubeblocks_helm/pika/templates/componentdefinition-codis-dashboard.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-codis-fe.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-codis-proxy.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-pika-etcd.yaml
  tools/kubeblocks_helm/pika/templates/componentdefinition-pika-group.yaml
  tools/kubeblocks_helm/pika/templates/script.yaml
Labels: ✏️ Feature
