Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-06, with the labels that each got.

#2694 feat:mget support multi get
  conf/pika.conf
  include/pika_kv.h
  src/pika_command.cc
  src/pika_kv.cc
  src/pika_server.cc
  tests/integration/cache_test.go
Labels: ✏️ Feature

#2668 feat:Add metrics
  codis/pkg/proxy/config.go
  codis/pkg/proxy/proxy.go
  codis/pkg/proxy/proxy_api.go
  codis/pkg/proxy/session.go
  codis/pkg/proxy/stats.go
  tools/pika_exporter/discovery/codis_dashboard.go
  tools/pika_exporter/exporter/metrics/parser.go
  tools/pika_exporter/exporter/metrics/proxy.go
  tools/pika_exporter/grafana/grafana_prometheus_pika_dashboard..json
Labels: ✏️ Feature

#2702 fix:refeator log
  src/pika_repl_bgworker.cc
Labels: ☢️ Bug, 4.0.0, 3.5.5

#2722 fix: release macos changed
  .github/workflows/release.yml
Labels: ☢️ Bug

#2729 fix:ttl will deafult 0 when keys have ttl
  src/pika_kv.cc
Labels: ☢️ Bug

#2723 fix:pkpatternmatchdel support stream type
  src/pika_admin.cc
  src/storage/include/storage/storage.h
  src/storage/src/storage.cc
Labels: bug, ☢️ Bug, 3.5.5

#2730 fix:ttl will deafult 0 when keys have ttl
  src/pika_kv.cc
  src/storage/include/storage/storage.h
  src/storage/src/redis.h
  src/storage/src/redis_strings.cc
  src/storage/src/storage.cc
Labels: ☢️ Bug, 4.0.0, 3.5.5

#2743 docs: modify run pika in docker readme
  README.md
Labels: 📒 Documentation, 4.0.0, 3.5.5

#2697 feat:thread purge
  conf/pika.conf
  include/pika_client_processor.h
  include/pika_conf.h
  include/pika_repl_bgworker.h
  include/pika_server.h
  src/net/include/backend_thread.h
  src/net/include/client_thread.h
  src/net/include/net_thread.h
  src/net/include/server_thread.h
  src/net/src/backend_thread.cc
  src/net/src/client_thread.cc
  src/net/src/dispatch_thread.cc
  src/net/src/holy_thread.h
  src/net/src/net_thread_name.h
  src/net/src/net_util.cc
  src/net/src/net_util.h
  src/net/src/thread_pool.cc
  src/pika_admin.cc
  src/pika_client_processor.cc
  src/pika_conf.cc
  src/pika_repl_client.cc
  src/pika_repl_server.cc
  src/pika_server.cc
  src/rsync_client.cc
  src/rsync_server.cc
Labels: ✏️ Feature, 4.0.0, 3.5.5

#2749 fix: keyspace causes heap-buffer-overflow
  src/pika_admin.cc
  src/storage/src/base_value_format.h
  src/storage/src/redis.cc
  src/storage/src/storage.cc
Labels: bug, ☢️ Bug, 4.0.0

#2744 fix: duplicate meta key read
  src/storage/src/redis.h
  src/storage/src/redis_hashes.cc
  src/storage/src/redis_lists.cc
  src/storage/src/redis_sets.cc
  src/storage/src/redis_streams.cc
  src/storage/src/redis_strings.cc
  src/storage/src/redis_zsets.cc
  src/storage/src/storage.cc
Labels: ☢️ Bug, 4.0.0

#2726 fix: some streams errors such as pkpatternmatchdel etc
  src/storage/src/base_filter.h
  src/storage/src/pika_stream_meta_value.h
  src/storage/src/redis_strings.cc
  src/storage/src/storage.cc
  src/storage/tests/keys_test.cc
Labels: bug, ☢️ Bug, 4.0.0

#2754 fix:CI run in branch 4.0
  .github/workflows/codeql.yml
  .github/workflows/codis.yml
  .github/workflows/pika.yml
  .github/workflows/tools_go.yml
Labels: ☢️ Bug

#2720 fix: Add isolation between string and hyperloglog( issue#2719)
  src/pika_command.cc
  src/storage/src/redis.h
  src/storage/src/redis_hyperloglog.cc
  src/storage/src/storage.cc
  src/storage/src/strings_value_format.h
  tests/assets/default.conf
  tests/unit/type/hyperloglog.tcl
Labels: ✏️ Feature, ☢️ Bug, 4.0.0, 3.5.5

#2759 fix:pksetexat should update cache
  include/pika_kv.h
  src/pika_command.cc
  src/pika_kv.cc
Labels: ☢️ Bug, 🧹 Updates

#2727 feat:Split the admin command out of the main thread
  conf/pika.conf
  include/pika_conf.h
  include/pika_server.h
  src/pika_admin.cc
  src/pika_client_conn.cc
  src/pika_conf.cc
  src/pika_list.cc
  src/pika_server.cc
Labels: ✏️ Feature, 4.0.0

#2763 fix:zverank return error
  src/storage/src/redis_zsets.cc
  tests/integration/zset_test.go
Labels: ☢️ Bug, 4.0.0, 3.5.5

#2767 fix: parse min-blob-size error when min-blob-size ends with unit
  src/pika_conf.cc
Labels: bug, ☢️ Bug, 4.0.0
