Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-04, with the labels that each got.

#2563 feat: support dynamic change max-total-wal-size
  include/pika_conf.h
  src/pika_admin.cc
  src/pika_server.cc
Labels: ✏️ Feature

#2572 fix:update operater config
  tools/kubeblocks_helm/pika-cluster/Chart.yaml
  tools/kubeblocks_helm/pika/Chart.yaml
  tools/kubeblocks_helm/pika/config/codis-dashboard.tpl
  tools/kubeblocks_helm/pika/config/codis-proxy.tpl
  tools/kubeblocks_helm/pika/config/pika-config.tpl
Labels: ☢️ Bug, 🧹 Updates

#2561 fix:some conf load error
  include/pika_conf.h
  src/pika_admin.cc
  src/pika_conf.cc
  tests/integration/server_test.go
Labels: ☢️ Bug

#2576 feat:add slotmigrate test
  tests/integration/slotmigrate_test.go
Labels: ✏️ Feature, 🧹 Updates

#2584 fix:info all slow when call info keyspace 1
  src/pika_db.cc
  tests/integration/admin_test.go
Labels: ☢️ Bug, 3.5.4, 4.0.0

#2585 fix:change cache-model to cache-mode
  include/pika_conf.h
  include/pika_define.h
  src/pika_admin.cc
  src/pika_command.cc
  src/pika_conf.cc
  src/pika_repl_bgworker.cc
  src/pika_slot_command.cc
  tests/integration/admin_test.go
Labels: ☢️ Bug, 3.5.4, 4.0.0

#2586 fix:tnx failed some times
  tests/integration/admin_test.go
  tests/integration/server_test.go
  tests/integration/txn_test.go
Labels: ☢️ Bug

#2590 fix:change deafult thread num
  conf/pika.conf
Labels: ☢️ Bug

#2596 fix:result wrong when commands call redis interface
  src/storage/src/redis_hashes.cc
  src/storage/src/redis_lists.cc
  src/storage/src/redis_sets.cc
  src/storage/src/redis_strings.cc
  src/storage/src/redis_zsets.cc
Labels: ☢️ Bug, 3.5.3, 4.0.0

#2600 fix:userbacklist && userpass
  include/pika_conf.h
  src/pika_admin.cc
  src/pika_conf.cc
Labels: ☢️ Bug

#2604 docs:354 version
  include/pika_version.h
Labels: 📒 Documentation

#2605 docs: changelog of v3.5.4-rc1
  CHANGELOG.MD
  CHANGELOG_CN.MD
Labels: 📒 Documentation, 3.5.4

#2617 docs:Update Manual compilation in README
  README.md
  README_CN.md
Labels: 🧹 Updates, 📒 Documentation

#2621 fix: fix strings_test
  src/storage/tests/strings_test.cc
Labels: ☢️ Bug, 🧹 Updates

#2624 fix:partial strings test fixed
  src/storage/src/storage.cc
  src/storage/tests/strings_test.cc
Labels: ☢️ Bug, 🧹 Updates

#2622 fix:replace mutex with atomic value in pika_conf
  include/pika_conf.h
  src/pstd/include/base_conf.h
  src/pstd/src/base_conf.cc
Labels: ☢️ Bug

#2603 fix:Add the output data of command 'info keyspace 0' to the output of com…
  src/pika_admin.cc
Labels: ✏️ Feature, ☢️ Bug
