Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-03, with the labels that each got.

#130 feat:import braft
  CMakeLists.txt
  build.sh
  cmake/boost.cmake
  cmake/braft.cmake
  cmake/brpc.cmake
  cmake/double-conversion.cmake
  cmake/findTools.cmake
  cmake/fmt.cmake
  cmake/folly.cmake
  cmake/gflags.cmake
  cmake/glog.cmake
  cmake/gtest.cmake
  cmake/leveldb.cmake
  cmake/libevent.cmake
  cmake/llhttp.cmake
  cmake/modules/glog/FindUnwind.cmake
  cmake/modules/glog/Findgflags.cmake
  cmake/modules/spdlog/fmtConfig.cmake
  cmake/openssl.cmake
  cmake/protobuf.cmake
  cmake/rocksdb.cmake
  cmake/spdlog.cmake
  cmake/unwind.cmake
  cmake/utils.cmake
  cmake/zlib.cmake
  src/CMakeLists.txt
  src/net/CMakeLists.txt
  src/pstd/CMakeLists.txt
  src/storage/CMakeLists.txt
  src/storage/include/storage/storage.h
  src/storage/src/base_filter.h
  src/storage/src/debug.h
  src/store.h
  tests/hash_test.go
Labels: help wanted, ✏️ Feature, 0.1.0, core, cluster

#197 fix: braft unknown bug
  cmake/braft.cmake
Labels: ☢️ Bug

#206 Revert: fix desappearing roles
  CMakeLists.txt
  cmake/braft.cmake
  cmake/brpc.cmake
  cmake/gflags.cmake
  cmake/protobuf.cmake
Labels: ☢️ Bug, Invalid PR Title

#209 fix: update brpc & cmake
  CMakeLists.txt
  cmake/braft.cmake
  cmake/brpc.cmake
  cmake/gflags.cmake
  cmake/protobuf.cmake
  src/CMakeLists.txt
  src/client.cc
  src/praft/praft.h
Labels: ☢️ Bug, 🧹 Updates

#218 fix:add class DB & sharedmutex
  src/base_cmd.cc
  src/base_cmd.h
  src/cmd_hash.cc
  src/cmd_keys.cc
  src/cmd_kv.cc
  src/cmd_list.cc
  src/cmd_set.cc
  src/cmd_zset.cc
  src/db.cpp
  src/db.h
  src/storage/include/storage/storage.h
  src/storage/src/storage.cc
  src/store.cc
  src/store.h
Labels: ☢️ Bug, ✏️ Feature

#228 docs: Update README.md
  README.md
  README_CN.md
  docs/images/pikiwidb-logo.png
Labels: 📒 Documentation, 🧹 Updates

#217 feat: support cmd `keys`
  src/base_cmd.h
  src/cmd_keys.cc
  src/cmd_keys.h
  src/cmd_table_manager.cc
  tests/key_test.go
Labels: ✏️ Feature

#222 feat:update string ut
  tests/string_test.go
Labels: ✏️ Feature, 🧹 Updates

#232 fix: Rebase import-braft to unstable
  .github/workflows/issue-translator.yml
  CMakeLists.txt
  README.md
  README_CN.md
  docs/images/pikiwidb-logo.png
  src/base_cmd.cc
  src/base_cmd.h
  src/cmd_hash.cc
  src/cmd_keys.cc
  src/cmd_keys.h
  src/cmd_kv.cc
  src/cmd_list.cc
  src/cmd_list.h
  src/cmd_set.cc
  src/cmd_set.h
  src/cmd_table_manager.cc
  src/cmd_zset.cc
  src/cmd_zset.h
  src/db.cpp
  src/db.h
  src/storage/include/storage/storage.h
  src/storage/src/storage.cc
  src/store.cc
  src/store.h
  tests/key_test.go
  tests/list_test.go
  tests/set_test.go
  tests/string_test.go
  tests/zset_test.go
Labels: ☢️ Bug, 📒 Documentation

#226 feat: Check point
  src/checkpoint_manager.cpp
  src/checkpoint_manager.h
  src/cmd_kv.cc
  src/db.cpp
  src/db.h
  src/pikiwidb.cc
  src/storage/include/storage/storage.h
  src/storage/src/storage.cc
  src/storage/src/storage_murmur3.h
  src/store.cc
  src/store.h
Labels: ✏️ Feature

#233 fix: Fix rebase bug
  src/base_cmd.h
  src/db.cpp
Labels: ☢️ Bug, 📒 Documentation

#235 feat: Adjust the UnboundedBuffer::PushData() function to C++ style
  src/common.cc
  src/multi.cc
  src/net/unbounded_buffer.cc
  src/net/unbounded_buffer.h
  src/replication.cc
Labels: ✏️ Feature

#236 fix: fix the GetStorage bug
  src/cmd_zset.cc
Labels: ☢️ Bug

#208 feat: cmd `pttl`
  src/base_cmd.h
  src/cmd_keys.cc
  src/cmd_keys.h
  src/cmd_table_manager.cc
  tests/key_test.go
Labels: ✏️ Feature
