Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-08, with the labels that each got.

#2840 fix:delete logs
  src/pika_cache_load_thread.cc
Labels: ☢️ Bug

#2836 fix: execute hincrby cmd more than one times after delete a field which is existing
  src/storage/src/redis_hashes.cc
  tests/integration/hash_test.go
Labels: ✏️ Feature, ☢️ Bug

#2841 fix: add switch for RTC cache read
  conf/pika.conf
  include/pika_client_conn.h
  include/pika_command.h
  include/pika_conf.h
  src/pika_client_conn.cc
  src/pika_command.cc
  src/pika_conf.cc
Labels: ✏️ Feature, ☢️ Bug

#2812 fix: multi command through cache
  src/pika_transaction.cc
Labels: ☢️ Bug, 4.0.1

#2839 fix: PkPatternMatchDel inconsistent between rediscache and db
  CMakeLists.txt
  conf/pika.conf
  include/pika_admin.h
  src/pika_admin.cc
  src/storage/include/storage/storage.h
  src/storage/src/redis.h
  src/storage/src/redis_hashes.cc
  src/storage/src/redis_hashes.h
  src/storage/src/redis_lists.cc
  src/storage/src/redis_lists.h
  src/storage/src/redis_sets.cc
  src/storage/src/redis_sets.h
  src/storage/src/redis_streams.cc
  src/storage/src/redis_streams.h
  src/storage/src/redis_strings.cc
  src/storage/src/redis_strings.h
  src/storage/src/redis_zsets.cc
  src/storage/src/redis_zsets.h
  src/storage/src/storage.cc
  src/storage/tests/keys_test.cc
Labels: ☢️ Bug, 3.5.5

#2833 feat:incr send binlog withttl
  include/pika_kv.h
  src/pika_kv.cc
  src/storage/include/storage/storage.h
  src/storage/src/redis.h
  src/storage/src/redis_strings.cc
  src/storage/src/storage.cc
  src/storage/tests/strings_test.cc
  tests/integration/replication_test.go
Labels: ✏️ Feature, 3.5.5, 4.0.1

#2829 feat:Added the periodically clearing serverlog function
  conf/pika.conf
  include/pika_conf.h
  include/pika_server.h
  src/pika_conf.cc
  src/pika_server.cc
Labels: ✏️ Feature, 3.5.5, 4.0.1

#2851 fix:355 CI
  .github/workflows/pika.yml
Labels: ☢️ Bug

#2844 test: fix multi bug and compatible ACL test
  include/pika_client_conn.h
  pikatests.sh
  src/pika_client_conn.cc
  src/pika_transaction.cc
  src/storage/include/storage/storage.h
  src/storage/src/storage.cc
  tests/assets/default.conf
  tests/conf/pika.conf
  tests/test_helper.tcl
  tests/unit/multi.tcl
Labels: ✏️ Feature, ☢️ Bug, 🧹 Updates, 3.5.5

#2853 fix: Revert change storage ttl time from seconds to milliseconds and clear space in CI after compile
  .github/workflows/pika.yml
  include/pika_cache.h
  include/pika_kv.h
  src/net/examples/performance/server.cc
  src/pika_admin.cc
  src/pika_bit.cc
  src/pika_cache.cc
  src/pika_cache_load_thread.cc
  src/pika_conf.cc
  src/pika_geo.cc
  src/pika_kv.cc
  src/pika_list.cc
  src/pika_server.cc
  src/pika_zset.cc
  src/pstd/include/env.h
  src/pstd/src/env.cc
  src/storage/include/storage/storage.h
  src/storage/src/base_data_value_format.h
  src/storage/src/base_filter.h
  src/storage/src/base_meta_value_format.h
  src/storage/src/base_value_format.h
  src/storage/src/lists_filter.h
  src/storage/src/lists_meta_value_format.h
  src/storage/src/redis.h
  src/storage/src/redis_hashes.cc
  src/storage/src/redis_lists.cc
  src/storage/src/redis_sets.cc
  src/storage/src/redis_streams.cc
  src/storage/src/redis_strings.cc
  src/storage/src/redis_zsets.cc
  src/storage/src/storage.cc
  src/storage/src/strings_filter.h
  src/storage/src/strings_value_format.h
  src/storage/src/zsets_filter.h
  src/storage/tests/keys_test.cc
  src/storage/tests/lists_filter_test.cc
  src/storage/tests/strings_filter_test.cc
  src/storage/tests/strings_test.cc
Labels: ☢️ Bug, 🧹 Updates, 4.0.1

#2846 fix: make flushall write binlog of flushdb
  include/pika_admin.h
  src/pika_admin.cc
Labels: ☢️ Bug, 3.5.5, 4.0.1

#2856 fix:update version
  include/pika_version.h
Labels: 🧹 Updates, 3.5.5

#2769 feat:Statistics ticker count
  conf/pika.conf
  include/pika_conf.h
  src/pika_admin.cc
  src/pika_conf.cc
  src/pika_server.cc
  src/storage/include/storage/storage.h
  src/storage/src/redis.cc
  src/storage/src/redis.h
Labels: ✏️ Feature, 4.0.1

#2859 docs: add platform rocky linux
  README.md
  README_CN.md
Labels: ✏️ Feature, 📒 Documentation

#2858 fix: blpop/brpop don't update cache
  include/pika_list.h
  src/net/src/worker_thread.cc
  src/pika_list.cc
Labels: ☢️ Bug, 🧹 Updates, 3.5.5, 4.0.1

#2863 fix: change the network time out in github action's pika.conf to avoid fake failure
  tests/integration/start_master_and_slave.sh
Labels: ☢️ Bug

#2862 fix: kill connections correctly in Net WorkThread
  src/net/src/worker_thread.cc
  src/net/src/worker_thread.h
  tests/integration/replication_test.go
  tests/integration/rsync_dynamic_reconfig.go
  tests/integration/start_master_and_slave.sh
Labels: ☢️ Bug, 3.5.5, 4.0.1

#2854 fix: make pika compactible with redis-sentinel
  .github/workflows/pika.yml
  include/pika_admin.h
  include/pika_dispatch_thread.h
  include/pika_repl_bgworker.h
  include/pika_server.h
  src/net/include/net_pubsub.h
  src/net/src/net_pubsub.cc
  src/pika_admin.cc
  src/pika_dispatch_thread.cc
  src/pika_repl_client.cc
  src/pika_server.cc
Labels: ☢️ Bug, 3.5.5, 4.0.1

#2864 fix:fix 355 CI
  tests/integration/start_master_and_slave.sh
Labels: ☢️ Bug

#2866 fix: revised some unexpected statement in go test
  tests/integration/replication_rename_test.go
  tests/integration/replication_test.go
Labels: ☢️ Bug, 🧹 Updates

#2867 docs:add 355 changelog
  CHANGELOG.MD
  CHANGELOG_CN.MD
Labels: ✏️ Feature, 📒 Documentation

#2877 fix: v3.5.5 changelog patch
  CHANGELOG.MD
  CHANGELOG_CN.MD
Labels: ☢️ Bug, 📒 Documentation

#2879 fix: rpushx cmd insert error
  src/pika_command.cc
Labels: ☢️ Bug
