Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-04, with the labels that each got.

#213 feat: hset/hdel wrote by braft and binlog
  CMakeLists.txt
  cmake/protobuf.cmake
  pikiwidb.conf
  src/CMakeLists.txt
  src/client.cc
  src/client.h
  src/config.cc
  src/config.h
  src/db.cpp
  src/db.h
  src/pikiwidb.cc
  src/pikiwidb.h
  src/praft/CMakeLists.txt
  src/praft/binlog.proto
  src/praft/praft.cc
  src/praft/praft.h
  src/praft/praft_service.h
  src/replication.h
  src/storage/CMakeLists.txt
  src/storage/include/storage/storage.h
  src/storage/src/batch.h
  src/storage/src/redis.cc
  src/storage/src/redis.h
  src/storage/src/redis_hashes.cc
  src/storage/src/storage.cc
  tests/consistency_test.go
Labels: ✏️ Feature

#267 fix: fix cmd hscan error and add test cases
  src/cmd_hash.cc
  tests/hash_test.go
Labels: ☢️ Bug, ✏️ Feature, 🧹 Updates

#257 feat: support cmd shutdown
  src/base_cmd.h
  src/cmd_admin.cc
  src/cmd_admin.h
  src/cmd_table_manager.cc
  tests/admin_test.go
Labels: ✏️ Feature

#292 fix: mac ci
  .github/workflows/pikiwidb.yml
Labels: ☢️ Bug

#294 fix: wrong client in go test
  tests/consistency_test.go
Labels: ☢️ Bug, 🧹 Updates
