Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2024-01, with the labels that each got.

#2257 feat: Dynamically set disable_auto_compaction
  conf/pika.conf
  include/pika_conf.h
  src/pika_admin.cc
  src/pika_conf.cc
  src/pika_server.cc
  src/storage/include/storage/storage.h
  src/storage/src/options_helper.cc
  src/storage/src/options_helper.h
  src/storage/src/redis.h
  src/storage/src/storage.cc
Labels: rocksdb, ✏️ Feature, 3.5.3, core

#2278 fix: incorrect initialization sequence about pika role and cmdstat_map(#2235)
  include/pika_cmd_table_manager.h
  include/pika_conf.h
  include/pika_server.h
  src/pika_admin.cc
  src/pika_client_conn.cc
  src/pika_cmd_table_manager.cc
  src/pika_conf.cc
  src/pika_server.cc
Labels: ☢️ Bug

#2222 feat: update benchmark_client to support more api commands
  tools/benchmark_client/CMakeLists.txt
  tools/benchmark_client/README.md
  tools/benchmark_client/benchmark_client.cc
Labels: tool, ✏️ Feature, 🧹 Updates, 📒 Documentation, 3.5.3

#2274 fix: delete binglog dead code
  include/pika_consensus.h
  include/pika_rm.h
  src/pika_command.cc
  src/pika_consensus.cc
  src/pika_rm.cc
Labels: ☢️ Bug, 3.5.3

#2013 feat:pika support acl
  conf/pika.conf
  include/acl.h
  include/pika_acl.h
  include/pika_admin.h
  include/pika_bit.h
  include/pika_client_conn.h
  include/pika_cmd_table_manager.h
  include/pika_command.h
  include/pika_conf.h
  include/pika_dispatch_thread.h
  include/pika_geo.h
  include/pika_hash.h
  include/pika_kv.h
  include/pika_list.h
  include/pika_pubsub.h
  include/pika_server.h
  include/pika_set.h
  include/pika_stream.h
  include/pika_transaction.h
  include/pika_zset.h
  src/acl.cc
  src/net/include/net_pubsub.h
  src/net/src/dispatch_thread.cc
  src/net/src/dispatch_thread.h
  src/net/src/net_pubsub.cc
  src/pika.cc
  src/pika_acl.cc
  src/pika_admin.cc
  src/pika_client_conn.cc
  src/pika_cmd_table_manager.cc
  src/pika_command.cc
  src/pika_conf.cc
  src/pika_dispatch_thread.cc
  src/pika_pubsub.cc
  src/pika_server.cc
  src/pika_slot_command.cc
  src/pstd/examples/hash_example.cc
  src/pstd/include/base_conf.h
  src/pstd/include/pstd_hash.h
  src/pstd/include/pstd_status.h
  src/pstd/include/pstd_string.h
  src/pstd/src/base_conf.cc
  src/pstd/src/pstd_hash.cc
  src/pstd/src/pstd_status.cc
  src/pstd/src/pstd_string.cc
  tests/assets/default.conf
  tests/assets/nodefaultuser.acl
  tests/assets/user.acl
  tests/assets/userwithselectors.acl
  tests/conf/pika.conf
  tests/instances.tcl
  tests/integration/server_test.go
  tests/support/test.tcl
  tests/support/util.tcl
  tests/test_helper.tcl
  tests/unit/acl.tcl
Labels: ✏️ Feature, 3.5.3

#2294 fix :fix acl complie
  src/pika_server.cc
Labels: ☢️ Bug, Invalid PR Title

#2310 fix: read acl file crash on Mac OS
  src/acl.cc
Labels: ☢️ Bug

#2318 feat: cache metrics
  tools/pika_exporter/config/info.toml
  tools/pika_exporter/exporter/conf.go
  tools/pika_exporter/exporter/metrics/cache.go
  tools/pika_exporter/exporter/metrics/parser.go
  tools/pika_exporter/exporter/pika.go
Labels: ✏️ Feature

#2337 fix: Redis Keys / Redis Memory not shown in topom dashboard
  codis/cmd/fe/assets/dashboard-fe.js
  codis/cmd/fe/assets/index.html
  codis/config/proxy.toml
  src/pika_command.cc
Labels: ☢️ Bug

#2253 fix:bitmap cache
  .github/workflows/pika.yml
  conf/pika.conf
  include/pika_conf.h
  include/pika_define.h
  include/pika_list.h
  src/pika_admin.cc
  src/pika_bit.cc
  src/pika_command.cc
  src/pika_conf.cc
  src/pika_kv.cc
  src/pika_list.cc
  src/pika_server.cc
  tests/integration/hash_test.go
  tests/integration/string_test.go
Labels: ☢️ Bug, 3.5.3, core

#2360 document: change LICENSE
  LICENSE
  src/pika_server.cc
Labels: document, Invalid PR Title
