Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2025-07, with the labels that each got.

#3129 fix: spop resp's format not compatible with php redis client
  src/pika_set.cc
Labels: bug, ☢️ Bug, 3.5.5

#3132 fix:Type Command Expired Key Consistency
  src/storage/src/redis_strings.cc
Labels: ☢️ Bug

#3134 fix:bug in time statistics format
  src/pika_admin.cc
Labels: ☢️ Bug

#3093 fix: when enable rate limiter auto tune, bandwidth should be higher a…
  src/pika_conf.cc
Labels: ☢️ Bug

#3133 fix:SETEX replication does not work
  src/pika_kv.cc
Labels: ☢️ Bug

#3135 feat: update zlib version
  CMakeLists.txt
Labels: ✏️ Feature, 🧹 Updates

#3142 feat: print pipeline num in slowlog
  include/pika_client_conn.h
  src/pika_client_conn.cc
Labels: ✏️ Feature

#3143 Revert "fix:bug in time statistics format"
  src/pika_admin.cc
Labels: ☢️ Bug, Invalid PR Title
