Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2025-02, with the labels that each got.

#2990 fix: hello command not return information of pika version
  src/pika_admin.cc
Labels: ☢️ Bug

#2989 fix: hello command not return information of pika version
  src/pika_admin.cc
Labels: ☢️ Bug

#3007 fix: Change the maximum range of setbit's offset to fit redis v3.5
  .github/workflows/pika.yml
  include/pika_define.h
  src/pika_bit.cc
  src/storage/src/redis_strings.cc
  tests/unit/type/bitops.tcl
  tools/pika-port/pika_port_3/pika_define.h
  tools/pika_migrate/include/pika_define.h
  tools/pika_migrate/src/pika_bit.cc
  tools/pika_migrate/src/pika_client_conn.cc
Labels: ☢️ Bug, 3.5.6

#2995 fix: Change the maximum range of setbit's offset to fit redis
  CMakeLists.txt
  include/pika_define.h
  src/pika_bit.cc
  src/storage/src/redis_strings.cc
  tests/integration/string_test.go
  tests/unit/type/bitops.tcl
  tools/manifest_generator/include/pika_define.h
  tools/pika-port/pika_port_3/pika_define.h
  tools/pika_migrate/include/pika_define.h
  tools/pika_migrate/src/pika_bit.cc
Labels: ☢️ Bug

#3009 feat:new big key count
  src/pika_admin.cc
  src/storage/include/storage/storage.h
  src/storage/src/redis.h
  src/storage/src/redis_hashes.cc
  src/storage/src/redis_lists.cc
  src/storage/src/redis_sets.cc
  src/storage/src/redis_zsets.cc
  src/storage/src/storage.cc
Labels: ✏️ Feature

#3018 fix: fix logo
  README.md
  src/pika.cc
Labels: ☢️ Bug, 📒 Documentation

#3020 add logo photo
  docs/images/pikiwidb-logo.png
Labels: ✏️ Feature, Invalid PR Title

#3021 fix: fix bgsave bug
  .github/workflows/pika.yml
  tests/integration/server_test.go
Labels: ☢️ Bug

#3025 fix: change version to 4.0.2
  include/pika_version.h
Labels: Invalid PR Title
