Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2025-03, with the labels that each got.

#3035 fix: fix ci
  tests/integration/server_test.go
Labels: ☢️ Bug

#3034 fix: Reduced ReadCache tags for some commands
  src/cache/include/cache.h
  src/cache/src/bit.cc
  src/cache/src/hash.cc
  src/cache/src/list.cc
  src/cache/src/set.cc
  src/cache/src/string.cc
  src/cache/src/zset.cc
  src/pika_cache.cc
  src/pika_cache_load_thread.cc
  src/pika_command.cc
  src/pika_conf.cc
  src/pika_hash.cc
Labels: ☢️ Bug

#3037 fix: Fixed an issue with asynchronous loading
  include/pika_cache.h
  src/cache/include/cache.h
  src/cache/src/bit.cc
  src/cache/src/hash.cc
  src/cache/src/list.cc
  src/cache/src/set.cc
  src/cache/src/string.cc
  src/cache/src/zset.cc
  src/pika_cache.cc
  src/pika_hash.cc
  src/pika_kv.cc
  src/pika_list.cc
Labels: ☢️ Bug

#3036 feat: summary different stages duration
  include/pika_client_conn.h
  include/pika_command.h
  include/pika_conf.h
  src/pika_admin.cc
  src/pika_client_conn.cc
  src/pika_command.cc
  src/pika_hash.cc
  src/pika_kv.cc
  src/pika_list.cc
  src/pika_set.cc
  src/pika_zset.cc
  src/pstd/include/stage_timer.h
Labels: ✏️ Feature

#3028 fix: Solved the problem of commandstate statistics duplication
  .github/workflows/pika.yml
  conf/pika.conf
  src/pika_client_conn.cc
Labels: ☢️ Bug

#3042 feat: Add p99 and slow command count
  CMakeLists.txt
  include/pika_admin.h
  include/pika_client_conn.h
  include/pika_cmd_table_manager.h
  src/pika_admin.cc
  src/pika_client_conn.cc
  src/pika_cmd_table_manager.cc
  tools/pika_exporter/config/info.toml
  tools/pika_exporter/exporter/client.go
  tools/pika_exporter/exporter/conf.go
  tools/pika_exporter/exporter/metrics/commandp99.go
  tools/pika_exporter/exporter/metrics/slowcommand.go
  tools/pika_exporter/exporter/pika.go
Labels: ✏️ Feature

#3044 feat: fix slowcmd log duration error with batch command && add proxy metrics
  codis/go.mod
  codis/go.sum
  codis/pkg/proxy/backend.go
  codis/pkg/proxy/request.go
  codis/pkg/proxy/session.go
  codis/pkg/proxy/stats.go
  codis/pkg/utils/log/log.go
  tools/pika_exporter/discovery/codis_dashboard.go
  tools/pika_exporter/exporter/metrics/parser.go
  tools/pika_exporter/exporter/metrics/proxy.go
Labels: ✏️ Feature, ☢️ Bug

#3038 fix: fix replication on pika node recovering
  codis/pkg/topom/topom_group.go
  codis/pkg/topom/topom_sentinel.go
  codis/pkg/utils/redis/client.go
  codis/pkg/utils/redis/sentinel.go
Labels: ☢️ Bug

#3039 fix: Fix problems found during testing
  src/storage/src/redis_strings.cc
Labels: ☢️ Bug, 🧹 Updates

#3047 fix: add big key
  include/pika_conf.h
  src/cache/include/config.h
  src/pika_admin.cc
  src/pika_cache_load_thread.cc
  src/pika_conf.cc
Labels: ✏️ Feature, ☢️ Bug

#3048 fix: add auth command to admin-thread-pool
  include/pika_conf.h
Labels: ✏️ Feature

#3049 fix: Example Repair the subjective and objective offline logic of noeds
  codis/pkg/topom/topom_sentinel.go
Labels: ☢️ Bug

#3050 fix: fix exit core
  conf/pika.conf
  include/pika_cmd_table_manager.h
  include/pika_server.h
  src/pika_cmd_table_manager.cc
  src/pika_server.cc
Labels: ☢️ Bug

#3052 Revert "fix: fix exit core"
  conf/pika.conf
  include/pika_cmd_table_manager.h
  include/pika_server.h
  src/pika_cmd_table_manager.cc
  src/pika_server.cc
Labels: ☢️ Bug, Invalid PR Title

#3055 Revert "feat:new big key count"
  src/pika_admin.cc
  src/storage/include/storage/storage.h
  src/storage/src/redis.h
  src/storage/src/redis_hashes.cc
  src/storage/src/redis_lists.cc
  src/storage/src/redis_sets.cc
  src/storage/src/redis_zsets.cc
  src/storage/src/storage.cc
Labels: ✏️ Feature, Invalid PR Title

#3054 fix: Fixed version information for Pika, Pika_exporter, Codis
  CMakeLists.txt
  codis/Makefile
  tools/pika_exporter/Makefile
  tools/pika_exporter/main.go
Labels: ☢️ Bug

#3056 fix: "fix slowcmd log duration error with batch command && add prox…
  codis/go.mod
  codis/go.sum
  codis/pkg/proxy/backend.go
  codis/pkg/proxy/request.go
  codis/pkg/proxy/session.go
  codis/pkg/proxy/stats.go
  codis/pkg/utils/log/log.go
  tools/pika_exporter/discovery/codis_dashboard.go
  tools/pika_exporter/exporter/metrics/parser.go
  tools/pika_exporter/exporter/metrics/proxy.go
Labels: ✏️ Feature, ☢️ Bug

#3057 fix: Fixed versions of Pika, Pika_exporter, Codis
  CMakeLists.txt
  codis/Makefile
  codis/cmd/dashboard/main.go
  codis/cmd/fe/main.go
  codis/cmd/ha/main.go
  codis/cmd/proxy/main.go
  codis/pkg/utils/version.go
  codis/version
  tools/pika_exporter/Makefile
  tools/pika_exporter/main.go
Labels: ☢️ Bug

#3062 fix: 355 cherrypick 40
  CMakeLists.txt
  codis/Makefile
  codis/cmd/dashboard/main.go
  codis/cmd/fe/main.go
  codis/cmd/ha/main.go
  codis/cmd/proxy/main.go
  codis/pkg/topom/topom_group.go
  codis/pkg/topom/topom_sentinel.go
  codis/pkg/utils/redis/sentinel.go
  codis/pkg/utils/version.go
  codis/version
  conf/pika.conf
  include/pika_cache.h
  include/pika_client_conn.h
  include/pika_command.h
  include/pika_conf.h
  include/pika_hash.h
  include/pika_kv.h
  src/cache/include/cache.h
  src/cache/include/config.h
  src/cache/src/bit.cc
  src/cache/src/hash.cc
  src/cache/src/list.cc
  src/cache/src/set.cc
  src/cache/src/string.cc
  src/cache/src/zset.cc
  src/pika_admin.cc
  src/pika_cache.cc
  src/pika_cache_load_thread.cc
  src/pika_client_conn.cc
  src/pika_command.cc
  src/pika_conf.cc
  src/pika_hash.cc
  src/pika_kv.cc
  src/pika_list.cc
  src/pika_set.cc
  src/pika_zset.cc
  src/pstd/include/stage_timer.h
  src/storage/src/redis_strings.cc
  tools/pika_exporter/Makefile
  tools/pika_exporter/main.go
Labels: ☢️ Bug

#3063 fix: update v4.0.2 changelog
  CHANGELOG.MD
  CHANGELOG_CN.MD
Labels: 🧹 Updates, 📒 Documentation

#3064 fix: Hotfix/correction maximum range
  include/pika_conf.h
Labels: ☢️ Bug

#3065 fix: fix correction maximum ranges
  include/pika_conf.h
Labels: ☢️ Bug

#3066 fix: update artifact version
  .github/workflows/release.yml
Labels: ☢️ Bug, 🧹 Updates
