Repository OpenAtomFoundation/pikiwidb, pull requests merged in 2025-06, with the labels that each got.

#3098 fix: Divide the auth command into the command thread pool in pipeling mode
  src/pika_client_conn.cc
Labels: ☢️ Bug

#3091 fix: ZRemrangebylex和zremrangebyscore等命令传参错误(#3090)
  src/pika_zset.cc
Labels: ☢️ Bug, 3.5.5

#3088 fix: rediscache race condition when read api meets rehashing
  include/pika_cache.h
  src/pika_cache.cc
Labels: ☢️ Bug

#3108 fix: ensure ZADD keeps the last score for duplicate members in a single command to align with Redis behavior
  src/storage/src/redis_zsets.cc
  tests/integration/zset_test.go
Labels: ✏️ Feature, ☢️ Bug

#3111 fix: skip processing command while associated connection has been closed
  src/net/include/net_conn.h
  src/net/src/net_conn.cc
  src/net/src/worker_thread.cc
  src/pika_client_conn.cc
Labels: ☢️ Bug

#2994 feat: Add PacificA data replication consistency scheme
  include/pika_admin.h
  include/pika_binlog.h
  include/pika_command.h
  include/pika_consensus.h
  include/pika_define.h
  include/pika_rm.h
  include/pika_server.h
  include/pika_slave_node.h
  src/pika_admin.cc
  src/pika_binlog.cc
  src/pika_command.cc
  src/pika_consensus.cc
  src/pika_db.cc
  src/pika_inner_message.proto
  src/pika_repl_bgworker.cc
  src/pika_repl_client.cc
  src/pika_repl_client_conn.cc
  src/pika_repl_server.cc
  src/pika_repl_server_conn.cc
  src/pika_rm.cc
  src/pika_server.cc
  tests/integration/cleanup_test.sh
  tests/integration/consistency_test.go
  tests/integration/options.go
  tests/integration/start_master_and_slave.sh
Labels: ✏️ Feature

#3100 fix: Specia Redis directives can cause pika service to crash
  conf/pika.conf
  include/pika_conf.h
  src/pika_cache.cc
  src/pika_conf.cc
  src/pika_kv.cc
  tests/integration/string_test.go
Labels: ☢️ Bug

#3114 fix: requirepass allows connection with any non-empty password (unstable)
  src/acl.cc
Labels: ☢️ Bug
